### ISSUE TITLE
请帮忙提供下opencore的版本说明，是否支持11.01 bigsur系统？

### ISSUE THREAD

**Issue by mythgp** [mashed-potatoes/HP-EliteDesk-800-G1-DM-OpenCore#1]
您好
   我有同样的机器，希望升级到11.01 bigsur系统，请问您上传的EFI是否有相关的配置说明和openocre版本信息，期待您的回复，谢谢！

**Comment by mashed-potatoes** [comment]
This build has been tested only with the latest macOS Catalina. You can try Big Sur yourself, all kexts should be compatible.

**Comment by mythgp** [comment]
请问这个具体的OC版本是多少？是0.65吗？另外，你可以正常休眠吗？

**Comment by mashed-potatoes** [comment]
0.6.5
there're no issues with sleep
